application: enobo-musicdb
version: 0-2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /api/.*
  script: resource.application
- url: /.*
  script: main.application
  